# Generated by Django 3.2.3 on 2021-05-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
